#ifndef STATECONTROLS_H
#define STATECONTROLS_H

#define DDR_MOTOR_CONTROL DDRA
#define PORT_MOTOR_CONTROL PORTA
#define PIN_MOTOR_CONTROL_RED 0
#define PIN_MOTOR_CONTROL_GREEN 1
#define PIN_MOTOR_CONTROL_BLUE 2

#define DDR_TEMPERATURE_CONTROL DDRA
#define PORT_TEMPERATURE_CONTROL PORTA
#define PIN_TEMPERATURE_CONTROL_RED 3
#define PIN_TEMPERATURE_CONTROL_GREEN 4
#define PIN_TEMPERATURE_CONTROL_BLUE 5


#endif